version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
        
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world

  print_my_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $MY_NAME

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_my_name
