version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "6c:9c:f6:6d:1f:ff:79:ea:2a:90:7a:58:0a:09:db:f1"

      - run: apk update && apk add openssh
      - run: ssh-keyscan 52.90.15.109 >> ~/.ssh/known_hosts

      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure